name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "docs"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## What’s Changed
  $CHANGES